# Generated by Django 3.2.13 on 2023-03-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230307_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
