# Generated by Django 3.2.13 on 2023-03-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='data',
            new_name='date',
        ),
    ]
