# Generated by Django 3.2.13 on 2023-04-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profileImageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
